addSbtPlugin("org.scoverage"    % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.4")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"       % "1.1.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-site"      % "1.3.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages"   % "0.6.2")
